spring.jpa.hibernate.ddl-auto=none
logging.path=logs
#logging.path=/Users/jcmeena/code_workspace/toursContainer/tours_productionize/logs
# logging.files - this config has been deprecated
logging.file.name=${logging.path}/myapp.log

